"""Ports (interfaces) of the application layer.

The application/domain code depends only on these Protocols; concrete
infrastructure (SQLAlchemy repositories, local/S3 storage) implements them.
"""

from collections.abc import AsyncIterator, Callable, Sequence
from pathlib import Path
from typing import Protocol, runtime_checkable

from src.domain.entities import Alert, StoredFile


@runtime_checkable
class FileRepository(Protocol):
    async def add(self, item: StoredFile) -> None: ...
    async def get(self, file_id: str) -> StoredFile | None: ...
    async def list_newest(self) -> Sequence[StoredFile]: ...
    async def delete(self, item: StoredFile) -> None: ...
    async def refresh(self, item: StoredFile) -> None: ...


@runtime_checkable
class AlertRepository(Protocol):
    async def add(self, alert: Alert) -> None: ...
    async def list_newest(self) -> Sequence[Alert]: ...


@runtime_checkable
class UnitOfWork(Protocol):
    files: FileRepository
    alerts: AlertRepository

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...  # noqa: ANN001


@runtime_checkable
class FileStorage(Protocol):
    def path(self, stored_name: str) -> Path: ...
    def exists(self, stored_name: str) -> bool: ...
    def delete(self, stored_name: str) -> None: ...
    def open_binary(self, stored_name: str): ...
    async def write_temp(self, chunks: AsyncIterator[bytes]) -> tuple[Path, int]: ...
    def commit(self, temp_path: Path, stored_name: str) -> Path: ...
    def discard(self, temp_path: Path) -> None: ...


UowFactory = Callable[[], UnitOfWork]

def make_uow_factory(unit_of_work_cls, session_factory) -> UowFactory:  # noqa: ANN001
    """Bind a concrete UnitOfWork class to a session factory."""
    return lambda: unit_of_work_cls(session_factory)
